export const GLOBAL_USERS = [
  {
    id: "1",
    name: "Alex Johnson",
    avatar_url: "https://i.pravatar.cc/150?img=1",
    days_completed: 68,
    points: 1240,
  },
  {
    id: "2",
    name: "Sarah Ahmed",
    avatar_url: "https://i.pravatar.cc/150?img=5",
    days_completed: 61,
    points: 1105,
  },
  {
    id: "3",
    name: "Marcus Lee",
    avatar_url: "https://i.pravatar.cc/150?img=3",
    days_completed: 57,
    points: 980,
  },
  {
    id: "4",
    name: "Priya Patel",
    avatar_url: "https://i.pravatar.cc/150?img=9",
    days_completed: 52,
    points: 890,
  },
  {
    id: "5",
    name: "Jordan Smith",
    avatar_url: "https://i.pravatar.cc/150?img=11",
    days_completed: 45,
    points: 760,
  },
  {
    id: "6",
    name: "You",
    avatar_url: "https://i.pravatar.cc/150?img=13",
    days_completed: 38,
    points: 634,
    isMe: true,
  },
  {
    id: "7",
    name: "Chris Wang",
    avatar_url: "https://i.pravatar.cc/150?img=15",
    days_completed: 31,
    points: 510,
  },
  {
    id: "8",
    name: "Fatima Malik",
    avatar_url: "https://i.pravatar.cc/150?img=16",
    days_completed: 24,
    points: 420,
  },
  {
    id: "9",
    name: "Tom Rivera",
    avatar_url: "https://i.pravatar.cc/150?img=18",
    days_completed: 17,
    points: 295,
  },
  {
    id: "10",
    name: "Emma Davis",
    avatar_url: "https://i.pravatar.cc/150?img=20",
    days_completed: 9,
    points: 140,
  },
];

export const FRIENDS_USERS = [
  {
    id: "2",
    name: "Sarah Ahmed",
    avatar_url: "https://i.pravatar.cc/150?img=5",
    days_completed: 61,
    points: 1105,
  },
  {
    id: "5",
    name: "Jordan Smith",
    avatar_url: "https://i.pravatar.cc/150?img=11",
    days_completed: 45,
    points: 760,
  },
  {
    id: "6",
    name: "You",
    avatar_url: "https://i.pravatar.cc/150?img=13",
    days_completed: 38,
    points: 634,
    isMe: true,
  },
  {
    id: "8",
    name: "Fatima Malik",
    avatar_url: "https://i.pravatar.cc/150?img=16",
    days_completed: 24,
    points: 420,
  },
  {
    id: "10",
    name: "Emma Davis",
    avatar_url: "https://i.pravatar.cc/150?img=20",
    days_completed: 9,
    points: 140,
  },
];
